---
abstract: 'Transform paths in @ARGV to absolute paths'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ARGV-Abs
requires:
  Cwd: 0
  File::Spec: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/dolmen/p5-ARGV-Abs
  repository: https://github.com/dolmen/p5-ARGV-Abs.git
version: 1.01
